### ISSUE TITLE
String as parameter of a function call

### ISSUE THREAD

**Issue by chriscamicas** [chriscamicas/abl-tmlanguage#7]
`string( foo ,"x(3)" ) + string( bar , "99" )`
![image](https://user-images.githubusercontent.com/7702519/45738913-ec411200-bbf1-11e8-98c8-c6959e8fb383.png)

**Comment by gquerret** [comment]
Not an issue anymore...

**Comment by chriscamicas** [comment]
was it fixed with a previous PR maybe?

**Comment by gquerret** [comment]
I just tried with the current version and previous version, and it works. I didn't do anything to fix this issue myself recently.

**Comment by chriscamicas** [comment]
ok, thanks, it's been automagically fixed then, I love this kind of issues :)
